apiVersion: v1
kind: Service
metadata:
  name: campaign-service
  namespace: clipdeck
  labels:
    app.kubernetes.io/name: campaign-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: clipdeck
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: campaign-service
